name: 'Composer (php-actions)'
description: 'Use the Composer CLI in your Github Actions.'
inputs:
  command:
    description: 'Composer command to run'
    required: true
    default: install --no-interaction

outputs:
  time:
    description: 'The time the action was run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - --working-dir=plugins/ups-algolia
    - --no-progress
branding:
  icon: 'package'
  color: 'purple'
